# Use Node.js as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend files to the working directory
COPY . .

# Expose port 3000 for the backend server
EXPOSE 3000

# Command to run the backend server
CMD ["node", "server.js"]
